### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ghostofiht** [MCISMc/StretchView#13]
Hi, I am making graphical contributions to open source projects. I have a design idea for StratchView. The current logo contains too many details. The small size of the icon makes the logo look bad. That's why I designed a simpler logo. 
 I can do this if you want a change in design. I left a few examples below to see what the logo looks like. I hope you like it. 

![sunu](https://user-images.githubusercontent.com/42060713/55512551-1b8a0e80-566c-11e9-9681-fafdc3df1194.jpg)
![sunu23](https://user-images.githubusercontent.com/42060713/55512552-1b8a0e80-566c-11e9-979f-5129d31655a3.jpg)
![sunu11](https://user-images.githubusercontent.com/42060713/55512719-77ed2e00-566c-11e9-9173-3fa9472ead2c.jpg)

**Comment by MCISMc** [comment]
it's very nice logo design, i appreciate your contribution and help @ghostofiht, ilike it a lot, just one thing can you try with color code #**0056b3**, for bottom-left corner, i think it will match with font colors i used and will look good, i'll be very much thank full of you for your contribution

**Comment by ghostofiht** [comment]
I'm glad you like it. I made the change you wanted for you. I made a few color combinations to make sure. Which one do you prefer?

![variation](https://user-images.githubusercontent.com/42060713/55581300-281e6d80-5725-11e9-8126-a2eae270908a.jpg)

**Comment by MCISMc** [comment]
@ghostofiht **image no. 4** looks quite convincing to me, again thanks for your contribution and help.

- These are the dimension in logo being required, 16x16, 32x32, 48x48, 128x128 & 256x256.

**Comment by ghostofiht** [comment]
I've uploaded the required files. I sent a PR.  [#14](https://github.com/MCISMc/StretchView/pulls/14)

**Comment by pishangujeniya** [comment]
Updated in PR #14
