### ISSUE TITLE
Different Shortcut Key Combination for PIP Mode

### ISSUE THREAD

**Issue by pishangujeniya** [MCISMc/StretchView#5]
Add specific different key combination for PIP (Picture-in-Picture) mode.

OS: Windows 10 Home

**Comment by MCISMc** [comment]
I wish if you can help me with it as I am busy these days.
@pishangujeniya 

Thanks

**Comment by pishangujeniya** [comment]
@MCISMc Yes Sure why not.

I would try by this weekend.

**Comment by MCISMc** [comment]
I have assigned it to you as collaborator for this task and have created a new branch with name : "**shortcut-pip**".

Waiting for a pull request to review.
Thanks

**Comment by pishangujeniya** [comment]
#7

**Comment by pishangujeniya** [comment]
#7 Fixed the issue and another bug for caching of images in the pull request #7
