### ISSUE TITLE
Disable Video Paused on YouTube

### ISSUE THREAD

**Issue by pishangujeniya** [MCISMc/StretchView#6]
Nowadays, when I play **YouTube** playlists of songs in one chrome tab and work then after approximately 30 minutes it shows pop-up asking to continue to play video, and I need to press "**_Yes_**" every time.

If this extension can provide somehow automation to click on that "**_Yes_**" then it would be better.

**Comment by MCISMc** [comment]
i'll check on that, see what can i do.

**Comment by MCISMc** [comment]
Did you try it with the Picture-in-Picture Mode, you would love to do your other works while your favorite playlist is being played uninterrupted, i am sure you won't get any warning after 30 minutes as your described while using PiP Mode.
